# The run config is used for both run mode and debug mode

[[configs]]
# the name of this task
name = "task"

# the program to run
program = ""

# the program arguments, e.g. args = ["arg1", "arg2"] 
args = []

# current working directory, optional
# cwd = "${workspace}"

# enviroment variables, optional
# [configs.env]
# VAR1 = "VAL1"
# VAR2 = "VAL2"
